### ISSUE TITLE
Diff - default parameters

### ISSUE THREAD

**Issue by herebebogans** [ampedandwired/bora#13]
Looks like the new diff parameter feature doesn't consider default parameters in the template (cfndsl in my test case) vs the current running stack?

eg If I have a running stack with parameter

> Foo = Bar

and a template with

>   "Parameters": {
>     "Foo": {
>       "Type": "String",
>       "Description": "Bar"
>     },

then a bora diff will show

```
Parameters
----------
-Foo - Bar
```

**Comment by ampedandwired** [comment]
Thanks, I didn't consider that case. I'll fix it.

**Comment by ampedandwired** [comment]
Still working on this. Needed a bit of refactoring which has taken longer than I expected. Should have something soon.

**Comment by ampedandwired** [comment]
Fixed in 1.4.1
