### ISSUE TITLE
Delete stack with no event polling

### ISSUE THREAD

**Issue by herebebogans** [ampedandwired/bora#15]
Hi

Thoughts on an override option (--no-events?) for delete to not poll the event output?

There's times when you just want to

Aws::CloudFormation::Client.delete_stack()

and not block on the event output.

**Comment by ampedandwired** [comment]
`--no-wait` perhaps?

**Comment by herebebogans** [comment]
I'm getting familiar with the codebase. I'll do a PR shortly.

**Comment by herebebogans** [comment]
You can close this - no longer required.
