### ISSUE TITLE
DisableRollBack option when running 'bora apply'

### ISSUE THREAD

**Issue by andrewoh531** [ampedandwired/bora#20]
Hello there!

AWS CloudFormation API has the option to specify a [DisableRollBack](http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html) parameter when running a `create-stack`.

Is this exposed through `bora` somehow?

**Comment by ampedandwired** [comment]
Not at the moment, but it sounds useful. I'll add it in.

**Comment by herebebogans** [comment]
Implies support for on_failure parameter as well ..

https://docs.aws.amazon.com/sdkforruby/api/Aws/CloudFormation/Client.html#create_stack-instance_method

**Comment by ampedandwired** [comment]
`on_failure` seems to provide a superset of the `disable_rollback` functionality, so we should probably use that. How about:

`bora apply <stack> --on-failure keep|rollback|delete`

**Comment by herebebogans** [comment]
Feels like it belongs in the yaml file at the same level as `capabilities` rather than an options cli param.

**Comment by ampedandwired** [comment]
Yeah, you might be right. I guess it's a question of whether or not you always want the same value for any given stack. I had in mind a workflow where things roll back by default but you may want to disable rollback on an ad-hoc basis to diagnose a problem. But I can see how in a "dev" environment you may want to permanently disable rollback.

**Comment by herebebogans** [comment]
I'll do a PR soon for this as I'm getting familiar with the stack_config / template_config inheritance patterns

**Comment by ampedandwired** [comment]
Thanks, appreciate it.
