### ISSUE TITLE
Ruby > 2.1 required

### ISSUE THREAD

**Issue by herebebogans** [ampedandwired/bora#3]
Can I put a note in the Readme.md mentioning that ruby > 2.1 is required due to the use of to_h?
Or is this best done in the gemspec?

http://guides.rubygems.org/specification-reference/#required_ruby_version

**Comment by ampedandwired** [comment]
Thanks, good catch. I added a note to the readme as well as a requirement in the gemspec.

Pushed a new version (1.1.0), as I haven't released in a while and the readme was actually quite out of date with the published version of the gem.
