### ISSUE TITLE
bora in bamboo

### ISSUE THREAD

**Issue by starchx** [ampedandwired/bora#35]
Hi Guys,

When I run bora in Bamboo tasks, it doesn't show the stack creation progress event logs until the whole task is finished (the output is being buffered somewhere). It works fine on my PC command line.
Just wondering do you have similar problems when run bora in Bamboo / Jenkins and what is your workaround?

**Comment by starchx** [comment]
In the task, I had to put "#!/bin/bash -l" on the top to be able to run bora command, otherwise bamboo just complains bora command not found..

**Comment by herebebogans** [comment]
@starchx 

Had similar issue with Jenkins console output. Are you invoking bora via Rake?

If so put this at the top of the Rakefile.

```
STDOUT.sync = true
```

If not - you might want to consider invoking bora though the included rake tasks via bundle with a Gemfile.

**Comment by starchx** [comment]
Thanks @herebebogans
I will definitely start using Rake ;)
